# fly.toml app configuration file generated for tracethat on 2024-01-12T12:52:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tracethat"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048