name: E2E tests

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.7"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: oven-sh/setup-bun@v2
      - run: go mod tidy
      - run: cd reporters/golang && go mod tidy && cd ../..
      - run: cd reporters/javascript/tracethat.dev && bun install && bun run build && cd ../..
      - run: cd reporters/python && ./install.sh && cd ../..   
      - run: cd frontend && bun install && cd ../..
      - run: cd e2e-tests && bun install && bunx playwright install --with-deps chromium && cd ../..
      - run: cd e2e-tests && bun run test && cd ../..
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 3
